Add Docker installation provision script

diff --git a/dev-ubuntu.yaml b/dev-ubuntu.yaml
--- a/dev-ubuntu.yaml
+++ b/dev-ubuntu.yaml
@@ -32,8 +32,54 @@ ssh:
 provision:
   - mode: system
     script: |
-      sudo apt install zsh git make neovim -y
-      sudo chown -R dev "{{.Param.dataMountPath}}"
+      #!/bin/bash
+      set -eux -o pipefail
+
+      # Setup data mount permissions
+      chown -R dev "{{.Param.dataMountPath}}"
+      
+      # Install and update packages
+      export DEBIAN_FRONTEND=noninteractive
+
+      apt-get update -y
+      apt-get dist-upgrade -y
+      apt-get autoremove -y
+      apt-get install zsh git make neovim -y
+
+  # Setup Docker
+  - mode: system
+    script: |
+      #!/bin/bash
+      set -eux -o pipefail
+
+      if command -v docker &>/dev/null; then
+        echo "Docker is installed. Exiting."
+        exit 0
+      fi
+
+      echo "Docker not found, proceeding with installation..."
+
+      export DEBIAN_FRONTEND=noninteractive
+
+      apt-get update -y
+
+      # Add Docker's official GPG key:
+      apt-get install ca-certificates curl -y
+      install -m 0755 -d /etc/apt/keyrings
+      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
+      chmod a+r /etc/apt/keyrings/docker.asc
+
+      # Add Docker's repository to Apt sources:
+      echo \
+        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
+        $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
+        tee /etc/apt/sources.list.d/docker.list > /dev/null
+      apt-get update -y
+
+      apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
+
+      groupadd docker
+      usermod -aG docker {{.User}}
 
   # Setup dotfiles
   - mode: user
